# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-29 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_classroompasscode'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='classroompasscode',
            name='passcode',
            field=models.CharField(default=b'70dd7db9-d', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
