# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-29 13:21
from __future__ import unicode_literals

import classroom.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20171229_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, to='classroom.Student'),
        ),
        migrations.AlterField(
            model_name='classroompasscode',
            name='passcode',
            field=models.CharField(default=classroom.models.generate_passcode, max_length=10, unique=True),
        ),
    ]
