# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-26 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='user',
            new_name='writer',
        ),
    ]
