# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-30 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0006_auto_20171230_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentlink',
            old_name='document',
            new_name='doc',
        ),
        migrations.AlterField(
            model_name='documentlink',
            name='permission',
            field=models.IntegerField(choices=[(0, 'can-view'), (1, 'can-comment'), (2, 'can-edit')], default=0),
        ),
    ]
