# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-30 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0008_documentlink_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='writing.Writer'),
        ),
        migrations.AlterField(
            model_name='documentlink',
            name='doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared', to='writing.Document'),
        ),
    ]
